force-app/main/default/objects/PerformanceMeasureResult__c/PerformanceMeasureResult__c.object-meta.xml
<CustomObject>
    <label>Performance Measure Result</label>
    <nameField>
        <displayFormat>PMR-{0}</displayFormat>
        <label>Performance Measure Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Measure Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PerformanceMeasureResult__c/fields/ErrorDetail__c.field-meta.xml
<CustomField>
    <fullName>ErrorDetail__c</fullName>
    <description>If the execution failed, the JSON serialized exception detail</description>
    <inlineHelpText>If the execution failed, the JSON serialized exception detail</inlineHelpText>
    <label>Error Detail</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PerformanceMeasureResult__c/fields/ExperimentName__c.field-meta.xml
<CustomField>
    <fullName>ExperimentName__c</fullName>
    <label>Experiment Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerformanceMeasureResult__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <description>The result of the experiment as a ParentJobResult enum. Either SUCCESS or UNHANDLED_EXCEPTION.</description>
    <inlineHelpText>The result of the experiment as a ParentJobResult enum. Either SUCCESS or UNHANDLED_EXCEPTION.</inlineHelpText>
    <label>Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PerformanceMeasureResult__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PerformanceMeasureResult__c/fields/SuiteName__c.field-meta.xml
<CustomField>
    <fullName>SuiteName__c</fullName>
    <description>The name of the test suite that this result came from</description>
    <inlineHelpText>The name of the test suite that this result came from</inlineHelpText>
    <label>Suite Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PerformanceExperimentFinalizer.cls
/**
 * @author aidan@processity.ai
 * @date 18/07/2024
 * @description If a experiment failed, then insert a record to mark the failure and continue from the next
 * step.
 * Run the current experiment if the running mode is Queueable Finalizer.
 */

public with sharing class PerformanceExperimentFinalizer implements Finalizer {
    private final PerformanceExperiment experiment;

    public PerformanceExperimentFinalizer(PerformanceExperiment experiment) {
        this.experiment = experiment;
    }

    public void execute(FinalizerContext context) {
        if (context.getResult() == ParentJobResult.UNHANDLED_EXCEPTION) {
            createErrorRecord(context.getException());
            experiment.executeNext();
        } else if (experiment?.mode == PerformanceTestingMode.QUEUEABLE_FROM_FINALIZER) {
            try {
                experiment.run();
            } catch (Exception ex) {
                createErrorRecord(ex);
            }
        }
    }

    private void createErrorRecord(Exception ex) {
        insert as system new PerformanceMeasureResult__c(
            Size__c = experiment.thisStep,
            SuiteName__c = experiment.suiteName,
            Result__c = ParentJobResult.UNHANDLED_EXCEPTION.name(),
            ExperimentName__c = experiment.getLabel(),
            ErrorDetail__c = ex.getTypeName() + ': ' + ex.getMessage() + '\n' + ex.getStackTraceString()
        );
    }
}